version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: digital_menu_db
    environment:
      POSTGRES_USER: menu_user
      POSTGRES_PASSWORD: MenuSecurePassword2026!
      POSTGRES_DB: digital_menu_saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
